GET http://localhost:8888/heroes.php HTTP/1.1

###

POST http://localhost:8888/hero_post.php HTTP/1.1

{"id": 0, "name": "Nuevo 3"}


###

PUT http://localhost:8888/hero_put.php HTTP/1.1

{"id": 6, "name": "Modificado"}


###

GET http://localhost:8888/hero_delete.php?9 HTTP/1.1
