GET http://localhost:8888/cliente.php HTTP/1.1

###

GET http://localhost:8888/producto.php HTTP/1.1

###

GET http://localhost:8888/producto.php?prodDescripcion=pro HTTP/1.1

###

GET http://localhost:8888/producto.php/15 HTTP/1.1

###

DELETE http://localhost:8888/producto.php/14 HTTP/1.1


###

POST http://localhost:8888/producto.php HTTP/1.1
Content-Type: application/json

{
    "prodDescripcion":"Nuevo Producto 2",
    "prodPrecio": 88
}


###

PUT http://localhost:8888/producto.php HTTP/1.1

{
    "prodId": 15,
    "prodDescripcion":"Celular Nokia",
    "prodPrecio": 345
}





### PEDIDO

GET http://localhost:8888/pedido.php HTTP/1.1

###

DELETE http://localhost:8888/pedido.php/32 HTTP/1.1


###

POST http://localhost:8888/pedido.php HTTP/1.1
Content-Type: application/json

{
    "pediFecha":"2020-12-15T00:00:00",
    "pediClienId": 33
}


###

PUT http://localhost:8888/pedido.php HTTP/1.1

{
    "pediId": 33,
    "pediFecha":"2020-12-14T00:00:00",
    "pediClienId": 25
}



### PEDIDO-DETALLE

GET http://localhost:8888/pedido-detalle.php?detaPediId=18 HTTP/1.1

###

DELETE http://localhost:8888/pedido-detalle.php/6 HTTP/1.1


###

POST http://localhost:8888/pedido.php HTTP/1.1
Content-Type: application/json

{"detaId":null,"detaPediId":null,"detaProdId":11,
"detaCantidad":2,"detaPrecio":3,
"detaBorrado":null,"detaFechaAlta":null,
"prodDescripcion":null}

###

PUT http://localhost:8888/pedido-detalle.php HTTP/1.1

{
"detaId":4,"detaPediId":17,"detaProdId":20,
"detaCantidad":1,"detaPrecio":11,
"detaFechaAlta":"2020-12-15T10:58:40.727",
"detaBorrado":0,"prodDescripcion":"Test1005"
}

